from __future__ import annotations
from pathlib import Path
import json
try: 
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib


def _load(p: Path): 
    return json.loads(Path(p).read_text())
def V(n): 
    return ['VAR', str(n)]
def N(x): 
    return ['NOT', x]
def A(*xs): 
    ys = []
    for x in xs: 
        if isinstance(x, list) and len(x) == 2 and x[0] == 'AND' and isinstance(x[1], list): 
            ys.extend(x[1])
        else: 
            ys.append(x)
    if not ys: 
        return ['CONST', 1]
    if len(ys) == 1: 
        return ys[0]
    return ['AND', ys]
def O(*xs): 
    ys = []
    for x in xs: 
        if isinstance(x, list) and len(x) == 2 and x[0] == 'OR' and isinstance(x[1], list): 
            ys.extend(x[1])
        else: 
            ys.append(x)
    if not ys: 
        return ['CONST', 0]
    if len(ys) == 1: 
        return ys[0]
    return ['OR', ys]

def _config(root: Path): 
    # Honor the same project-config resolution contract as the compiler entrypoints.
    # This is essential for corpus/third-party BIO projects selected with
    # BIO2RTL_WORKSPACE_CONFIG; never silently fall back to the benchmark TOML.
    from .project_inputs import load_config
    _, cfg = load_config(Path(root))
    return cfg

def gpio_core_input_map(root: Path)->dict[int, str]: 
    """Resolve BIO GPIO numbers to compiler-owned semantic core input nets.

    The user declares only external pin names and Baochip GPIO numbers. Internal
    net spellings are generated by bio2rtl and are never TOML inputs.
    """
    from .physical_interface import gpio_input_map_from_config
    cfg = _config(root)
    return gpio_input_map_from_config(cfg)

def global_clock_reset(root: Path)->tuple[str, str]: 
    from .physical_interface import gpio_input_map_from_config
    cfg = _config(root); source = str((cfg.get('clock', {}) or {}).get('source', ''))
    by_name = {str(x['name']): int(x['gpio']) for x in cfg.get('io', [])}
    if source not in by_name: 
        raise ValueError(f'clock source {source!r} not declared by [[io]]')
    clock = gpio_input_map_from_config(cfg)[by_name[source]]
    return clock, 'reset'

def _contract(root: Path, name: str): 
    p = root/'build/semantic_neutral_contracts'/f'{name}.json'
    return _load(p) if p.exists() else None

def _bit_pairs_from_contract(d: dict, semantic_source: str|None = None): 
    rows = []
    for i, x in enumerate(d.get('dffs', [])): 
        if semantic_source is not None: 
            ss = x.get('semantic_source')
            if ss is not None and str(ss)!=str(semantic_source): 
                continue
        bit = x.get('semantic_state_bit', x.get('semantic_bit', i))
        rows.append((int(bit), str(x['q']), str(x['qb'])))
    return sorted(rows)

def load_hold_naming(bank: dict)->list[dict]: 
    """Deterministic generic naming/orientation policy for synchronous load/hold banks."""
    role = str(bank['role']); src = str(bank['semantic_source']); bits = list(map(int, bank.get('semantic_bits', range(int(bank.get('width', 0))))))
    data = bank.get('data_semantics', {})
    if role == 'selector_context': 
        stem = 'p12'  # stable interface spelling selected by role, not semantic source name
    elif role == 'observation_snapshot': 
        stem = 'snap'
    elif role == 'gpio_payload' and src == 'G_DATA': 
        stem = 'gdata'
    elif role == 'gpio_payload' and src == 'G_DIR': 
        stem = 'gdirp' if bool(data.get('invert')) else 'gdir'
    else: 
        stem = f'{role}_{src}'.lower().replace('-', '_')
    out = []
    for i, b in enumerate(bits): 
        q = f'{stem}{i}' if stem in ('snap', 'gdata', 'gdirp') else f'{stem}_{i}'
        # Preserve the compact stable names used by the existing project where the source itself
        # is an architecture register.  This is naming policy only, not semantic selection.
        if role == 'selector_context': 
            q = f'p12_{i}'
        if role == 'gpio_payload' and src == 'G_DIR' and bool(data.get('invert')): 
            qb = f'gdir{i}'
        else: 
            qb = f'{q}_n'
        # If the semantic payload is the complement of the captured serial word, absorb the
        # inversion into the complementary DFF output instead of inserting a data inverter.
        # Q stores the raw capture; QB is then the semantic state bit.  This is generic
        # complementary-output polarity selection, not protocol-specific naming.
        semantic_on = 'qb' if bool(data.get('invert')) else 'q'
        out.append({'semantic_bit': b, 'q': q, 'qb': qb, 'semantic_on': semantic_on})
    return out

def _shared_counter_pairs(root: Path, source: str): 
    root = Path(root)
    cert = root/'build/generated_certificates/shared_counter.json'
    if not cert.exists(): 
        return None
    c = _load(cert); inc = str((c.get('semantic_sources') or {}).get('increment_source', ''))
    if str(source)!=inc: 
        return None
    d = _contract(root, 'shared_counter_and_event_latch')
    if d: 
        bits = (d.get('neutral_interface_binding', {}) or {}).get('counter_bits', [])
    else: 
        try: 
            from .neutral_bindings import resolve_shared_counter_interface_binding
            plan = resolve_shared_counter_interface_binding(root, include_roles = False)
        except (FileNotFoundError, KeyError, ValueError): 
            plan = None
        bits = (plan or {}).get('counter_bits', [])
    if not bits: 
        return None
    return [(i, str(x['net']), str(x['complement'])) for i, x in enumerate(bits)]


def _direct_state_pairs(root: Path, source: str): 
    root = Path(root)
    cert = root/'build/generated_certificates/direct_state_recurrence.json'
    if not cert.exists() or str(_load(cert).get('semantic_source'))!=str(source): 
        return None
    d = _contract(root, 'direct_protocol_state')
    if d: 
        return [(int(x.get('semantic_state_bit', i)), str(x['q']), str(x['qb'])) for i, x in enumerate(d.get('dffs', []))]
    try: 
        from .neutral_bindings import resolve_direct_state_interface_binding
        plan = resolve_direct_state_interface_binding(root, include_roles = False)
    except (FileNotFoundError, KeyError, ValueError): 
        plan = None
    bits = (plan or {}).get('state_bits', [])
    if not bits: 
        return None
    return [(i, str(x['net']), str(x['complement'])) for i, x in enumerate(bits)]


def non_dff_state_pair(root: Path, source: str|None = None): 
    """Return deterministic Q/QB names for a recovered 1-bit non-DFF semantic state.

    Naming is derived from the semantic source, not from a generated component or a
    benchmark-specific interface-binding cache.  This keeps legal-role discovery acyclic.
    """
    root = Path(root); arch = _load(root/'build/architecture_ir_v16_stage3_seedless.json')
    rows = [x for x in arch.get('non_dff_state', []) if int(x.get('bits', 0)) == 1]
    if source is not None: 
        rows = [x for x in rows if str(x.get('semantic_source', '')) == str(source)]
    if len(rows)!=1: 
        return None
    src = str(rows[0].get('semantic_source', '')).strip()
    if not src: 
        return None
    # Stable generic spelling: normalized semantic source and its complement.
    import re
    q = re.sub(r'[^A-Za-z0-9_]+', '_', src).strip('_').lower()
    if not q: 
        q = 'state_latch'
    return (src, q, f'{q}_n')


def _natural_event_pairs(root: Path, source: str): 
    root = Path(root); p = root/'build/architecture_ir_v16_stage3_seedless.json'
    if not p.exists(): 
        return None
    arch = _load(p)
    rows = [x for x in arch.get('physical_state', [])
          if str(x.get('semantic_source', '')) == str(source)
          and x.get('proof') == 'phase_ir_natural_storage'
          and x.get('clock_domain') == 'EVENT_ONLY']
    if len(rows)!=1: 
        return None
    e = rows[0]; bits = list(map(int, e.get('semantic_bits', [])))
    if not bits: 
        bits = list(range(int(e.get('bits', 0))))
    import re
    src = re.sub(r'[^A-Za-z0-9_]', '_', str(source))
    return [(b, f'nat_{src}_b{b}', f'nat_{src}_b{b}_n') for b in bits]

def semantic_state_pairs(root: Path, source: str, current_banks: list[dict]|None = None): 
    root = Path(root)
    z = _shared_counter_pairs(root, source)
    if z: 
        return sorted(z)
    z = _direct_state_pairs(root, source)
    if z: 
        return sorted(z)
    z = _natural_event_pairs(root, source)
    if z: 
        return sorted(z)
    for b in current_banks or []: 
        if str(b.get('semantic_source')) == str(source): 
            rows = []
            for x in load_hold_naming(b): 
                if str(x.get('semantic_on', 'q')) == 'qb': 
                    rows.append((int(x['semantic_bit']), str(x['qb']), str(x['q'])))
                else: 
                    rows.append((int(x['semantic_bit']), str(x['q']), str(x['qb'])))
            return rows
    return None

def _canon(e): 
    if not isinstance(e, list): 
        return e
    if not e: 
        return tuple()
    op = e[0]
    if op == 'VAR': 
        return ('VAR', str(e[1]))
    if op == 'CONST': 
        return ('CONST', int(e[1]))
    if op == 'NOT': 
        x = _canon(e[1])
        if isinstance(x, tuple) and x and x[0] == 'NOT': 
            return x[1]
        return ('NOT', x)
    if op in ('AND', 'OR'): 
        xs = []
        raw = e[1] if len(e) == 2 and isinstance(e[1], list) else e[1:]
        for x in raw: 
            c = _canon(x)
            if isinstance(c, tuple) and c and c[0] == op: 
                xs.extend(c[1])
            else: 
                xs.append(c)
        return (op, tuple(sorted(xs, key = repr)))
    return tuple([op]+[_canon(x) if isinstance(x, list) else x for x in e[1:]])

def _existing_comb_outputs(root: Path): 
    out = {}
    d = root/'build/semantic_neutral_contracts'
    if not d.exists(): 
        return out
    for p in sorted(d.glob('*.json')): 
        try: 
            c = _load(p)
        except Exception: 
            continue
        for n, e in c.get('combinational_outputs', {}).items(): 
            out[str(n)] = e
    return out

def reuse_exact_helper(root: Path, e): 
    """Replace an expression by an already-produced named helper when structurally exact.

    This is a cost/graph-reuse decision only; helper names have no semantic significance.
    """
    want = _canon(e); hits = []
    for n, x in _existing_comb_outputs(Path(root)).items(): 
        if _canon(x) == want: 
            hits.append(n)
    return V(sorted(hits)[0]) if hits else e

def semantic_eq_expr(root: Path, source: str, value: int, current_banks: list[dict]|None = None, *, reuse_helpers: bool = True): 
    pairs = semantic_state_pairs(Path(root), str(source), current_banks)
    if not pairs: 
        raise ValueError(f'no semantic->physical state projection for {source}')
    width = len(pairs)
    if int(value)<0 or int(value)>=(1<<width): 
        raise ValueError(f'{source}=={value} does not fit {width} projected bits')
    terms = []
    for bit, q, qb in pairs: 
        terms.append(V(q if ((int(value)>>bit)&1) else qb))
    e = A(*terms)
    return reuse_exact_helper(Path(root), e) if reuse_helpers else e

def semantic_predicate_expr(root: Path, pred: dict, current_banks: list[dict]|None = None, *, reuse_helpers: bool = True): 
    if pred.get('kind')!='semantic_equality_conjunction': 
        raise ValueError(pred)
    e = A(*(semantic_eq_expr(root, a['source'], int(a['value']), current_banks, reuse_helpers = reuse_helpers) for a in pred.get('atoms', [])))
    return reuse_exact_helper(Path(root), e) if reuse_helpers else e

def _predicate_basis(root: Path): 
    phase = _load(root/'build/semantic/phase40.ir.json')
    return {str(x['id']): x['expression'] for x in phase.get('predicate_basis', [])}

def resolve_shift_observation_bit(root: Path, semantic_source: str, bit: int)->str: 
    """Resolve a semantic old-shift bit through the proof-backed quotient observation plan."""
    root = Path(root)
    d = _contract(root, 'shift_observation_quotient')
    if d: 
        plan = d.get('neutral_interface_binding', {}) or {}
    else: 
        try: 
            from .neutral_bindings import resolve_shift_interface_binding
            plan = resolve_shift_interface_binding(root, include_roles = False) or {}
        except (FileNotFoundError, KeyError, ValueError): 
            plan = {}
    if not plan: 
        raise ValueError('shift quotient interface unavailable')
    cert = _load(root/'build/generated_certificates/shift_quotient.json')
    if str(cert.get('source_register', cert.get('semantic_source', semantic_source))) not in (str(semantic_source), 'None'): 
        pass
    basis = _predicate_basis(root)
    for x in plan.get('observation_outputs', []): 
        e = basis.get(str(x.get('predicate_id')))
        if not (isinstance(e, list) and len(e) == 3 and e[0] == 'EQ'): 
            continue
        lhs, rhs = e[1], e[2]
        if not (isinstance(lhs, list) and len(lhs) == 3 and lhs[0] == 'BIT_VALUE' and lhs[1] == ['REG', str(semantic_source)] and int(lhs[2]) == int(bit)): 
            continue
        if not (isinstance(rhs, list) and rhs[0] == 'CONST'): 
            continue
        c = int(rhs[1]); inv = bool(x.get('invert'))
        if (c == 0 and inv) or (c == 1 and not inv): 
            return str(x['net'])
    raise ValueError(f'no proof-backed quotient observation output for {semantic_source}[{bit}]')


def external_input_bit(root: Path, bit: int)->str: 
    m = gpio_core_input_map(Path(root))
    if int(bit) not in m: 
        raise ValueError(f'no TOML physical-support input binding for BIO GPIO bit {bit}')
    return m[int(bit)]

def load_data_exprs(root: Path, bank: dict)->list: 
    d = bank['data_semantics']; bits = list(map(int, bank.get('semantic_bits', range(int(bank.get('width', d.get('width', 0)))))))
    width = len(bits) if bits else int(d.get('width', 0)); kind = str(d.get('kind'))
    if kind == 'serial_capture_lsb_first_2bit': 
        if width!=2: 
            raise ValueError('serial_capture_lsb_first_2bit requires width=2')
        # Inverted semantic payloads use complementary-output orientation (semantic_on=QB),
        # so the physical D input remains the raw captured word.
        return [V(external_input_bit(root, int(d['sampled_input_bit']))), V(resolve_shift_observation_bit(root, str(d['shift_source']), int(d['shift_bit'])))]
    if kind == 'external_input_slice': 
        lo = int(d['lo']);hi = int(d['hi']); vals = [V(external_input_bit(root, b)) for b in range(lo, hi+1)]
        if bool(d.get('invert')): 
            vals = [N(x) for x in vals]
        return vals
    raise ValueError(f'unsupported semantic load-data source {d}')

def discover_load_hold_binding(root: Path)->dict|None: 
    root = Path(root); p = root/'build/generated_certificates/load_hold_semantic_recurrence.json'
    if not p.exists(): 
        return None
    cert = _load(p)
    if cert.get('status')!='PASS': 
        return None
    banks = cert.get('banks', []); clock, reset = global_clock_reset(root); out = []
    role_map = {'selector_context': 'selector_context', 'observation_snapshot': 'observation_snapshot', 'G_DATA': 'payload_data', 'G_DIR': 'payload_direction_complement'}
    for b in banks: 
        naming = load_hold_naming(b); data = load_data_exprs(root, b)
        if len(naming)!=len(data): 
            raise ValueError(f'bank width/data mismatch {b.get("semantic_source")}')
        pred = b['load_semantics']['minimal_load_predicate']; load = semantic_predicate_expr(root, pred, banks, reuse_helpers = False)
        out.append({
          'role': role_map.get(str(b.get('semantic_source')), str(b.get('role'))), 
          'architecture_role': str(b.get('role')) if str(b.get('role'))!='gpio_payload' else ('gpio_direction_payload' if str(b.get('semantic_source')) == 'G_DIR' else 'gpio_data_payload'), 
          'semantic_source': str(b['semantic_source']), 
          'load_expression': load, 
          'semantic_load_predicate': pred, 
          'bits': [{'semantic_bit': int(n['semantic_bit']), 'q': n['q'], 'qb': n['qb'], 'semantic_on': n.get('semantic_on', 'q'), 'load_data': x} for n, x in zip(naming, data)], 
        })
    return {
      'version': 'bio2rtl-auto-load-hold-bank-plan-v1', 'clock': clock, 'reset': reset, 'banks': out, 
      'resolved_from': 'semantic_load_hold_recurrence+generic_semantic_projection+project_toml', 
      'semantic_authority_sha256': __import__('hashlib').sha256(p.read_bytes()).hexdigest(), 
      'interface_binding_cache_used': False, 
    }
